### ISSUE TITLE
Wrong reference for the hyperlink to Apply section

### ISSUE THREAD

**Issue by amrs-tech** [fossasia/blog.fossasia.org#1]
The hyperlink Apply that references the Apply page of fossasia.org ("fossasia.org/apply.html") is wrong because the destination page doesn't exist. It may be corrected by replacing it with the hyperlink ("fossasia.org/apply")

**Comment by mariobehling** [comment]
Thanks. I fixed it.

**Comment by amrs-tech** [comment]
Thanks.
