### ISSUE TITLE
Propose free bootstrap design theme

### ISSUE THREAD

**Issue by mariobehling** [fossasia/blog.fossasia.org#1]
We are looking for a free bootstrap theme for Drupal 7, that matches the design of the main page more closely. The idea is to stick to the design theme as close as possible. We want to little custom changes, so we do not need to re-configure things when there are updates.

**Comment by Abuissink** [comment]
It's not a Drupal theme, just a pure Bootstrap one, but would something like this http://startbootstrap.com/template-overviews/clean-blog/ be nice? I've never used Drupal so I don't know how hard it is to port a Bootstrap theme over to Drupal.

**Comment by mariobehling** [comment]
Thank you. Looks great. It is quite some work to get a theme ported to Drupal. Would be great if you look into it.

**Comment by sudheesh001** [comment]
Why not use Jekyll instead ? Or did I miss something here ?
Sudheesh Singanamalla

Date: Thu, 11 Feb 2016 21:37:07 -0800

**Comment by mariobehling** [comment]
@sudheesh001 We don't want to start a technology discussion here. I am sorry, but I need to be a bit time savy. The current blog is on Drupal and we simply look for a new theme that is more suitable.

**Comment by sudheesh001** [comment]
Ah that'd make sense :+1: Then it's drupal all the way. I thought this could take some time and that's why i proposed jekyll. Sorry about that.

**Comment by Abuissink** [comment]
https://www.drupal.org/project/bootstrap I'm not sure how exactly you'd use this but "this base theme bridges the gap between Drupal and the Bootstrap Framework". I can find out more about this if you'd like.
